import { Pressable, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";

export default function AccountScreen() {
  return <ScreenContainer edges={["top", "left", "right", "bottom"]} containerClassName="bg-[#F7F7F5]"><View style={styles.content}><Text style={styles.eyebrow}>YOUR SPACE</Text><Text style={styles.title}>Account</Text><View style={styles.profileCard}><View style={styles.avatar}><Text style={styles.avatarText}>J</Text></View><View><Text style={styles.name}>Jordan Lee</Text><Text style={styles.email}>jordan@example.com</Text></View></View><Text style={styles.section}>SETTINGS</Text><Pressable style={styles.row}><MaterialIcons name="payment" size={20} color="#5E7A3B" /><Text style={styles.rowText}>Payment method</Text><Text style={styles.rowMeta}>•••• 4242</Text><MaterialIcons name="chevron-right" size={20} color="#9AA095" /></Pressable><Pressable style={styles.row}><MaterialIcons name="help-outline" size={20} color="#5E7A3B" /><Text style={styles.rowText}>Help and support</Text><MaterialIcons name="chevron-right" size={20} color="#9AA095" /></Pressable><Pressable style={styles.row}><MaterialIcons name="tune" size={20} color="#5E7A3B" /><Text style={styles.rowText}>Preferences</Text><MaterialIcons name="chevron-right" size={20} color="#9AA095" /></Pressable><Text style={styles.footer}>Ride Booking · Passenger preview</Text></View></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 20 }, eyebrow: { color: "#6F746B", fontSize: 11, letterSpacing: 1.5, fontWeight: "800", marginTop: 8 }, title: { color: "#111111", fontSize: 30, lineHeight: 36, fontWeight: "800", marginTop: 7, marginBottom: 20 }, profileCard: { backgroundColor: "#111111", borderRadius: 22, padding: 18, flexDirection: "row", alignItems: "center", marginBottom: 28 }, avatar: { width: 50, height: 50, borderRadius: 25, backgroundColor: "#B8F36B", alignItems: "center", justifyContent: "center", marginRight: 13 }, avatarText: { color: "#111111", fontSize: 21, fontWeight: "800" }, name: { color: "#FFFFFF", fontSize: 17, fontWeight: "800" }, email: { color: "#BDC4B8", fontSize: 13, marginTop: 4 }, section: { color: "#6F746B", fontSize: 11, letterSpacing: 1.5, fontWeight: "800", marginBottom: 8 }, row: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E3E5DF", minHeight: 58, borderRadius: 15, paddingHorizontal: 15, flexDirection: "row", alignItems: "center", marginBottom: 9 }, rowText: { flex: 1, color: "#111111", fontSize: 14, fontWeight: "700", marginLeft: 11 }, rowMeta: { color: "#6F746B", fontSize: 13, marginRight: 8 }, footer: { color: "#9AA095", textAlign: "center", fontSize: 12, marginTop: 28 } });
